title: CV | A jekyll template
description:  A beautiful template for your CV.
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    -/currículo

exclude:
  - docker-compose.yml
